<div class="row">
    <div class="card">
        <div class="card-header" style="text-align:center">CADASTRO DE PERGUNTA
        </div>
        <div class="card-body">
            <div class="modal-body no-padding">
                <div class="row">
                    <div class="col-12">
                        <form id="form">
                            <div class="form-group col-md-12">
                                <label for="descricao">Pergunta</label>
                                <textarea type="text" id="descricao" name="descricao" class="form-control"></textarea>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="dificuldade">Dificuldade</label> <br>
                                <input type="radio" id="dificuldade" name="dificuldade" value="Fácil"></input>
                                <label for="dificuldade">Fácil</label>
                                <input type="radio" id="dificuldade" name="dificuldade" value="Média"></input>
                                <label for="dificuldade">Média</label>
                                <input type="radio" id="dificuldade" name="dificuldade" value="Difícil"></input>
                                <label for="dificuldade">Difícil</label>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="alternativa1">Alternativa 1</label>
                                <input type="text" id="alternativa1" name="alternativa1" class="form-control">
                            </div>
                            <div class="form-group col-md-12">
                                <label for="alternativa2">Alternativa 2</label>
                                <input type="text" id="alternativa2" name="alternativa2" class="form-control">
                            </div>
                            <div class="form-group col-md-12">
                                <label for="alternativa3">Alternativa 3</label>
                                <input type="text" id="alternativa3" name="alternativa3" class="form-control">
                            </div>
                            <div class="form-group col-md-12">
                                <label for="alternativa4">Alternativa 4</label>
                                <input type="text" id="alternativa4" name="alternativa4" class="form-control">
                            </div>
                            <div class="form-group col-md-12">
                                <label for="alternativa5">Alternativa 5</label>
                                <input type="text" id="alternativa5" name="alternativa5" class="form-control">
                            </div>
                            <div class="form-group col-md-12">
                                <label for="alternativaCorreta">Alternativa Correta</label> <br>
                                <input type="radio" id="alternativaCorreta1" name="alternativaCorreta" value="1"></input>
                                <label for="alternativaCorreta1">Alternativa 1</label>
                                <br>
                                <input type="radio" id="alternativaCorreta2" name="alternativaCorreta" value="2"></input>
                                <label for="alternativaCorreta2">Alternativa 2</label>
                                <br>
                                <input type="radio" id="alternativaCorreta3" name="alternativaCorreta" value="3"></input>
                                <label for="alternativaCorreta3">Alternativa 3</label>
                                <br>
                                <input type="radio" id="alternativaCorreta4" name="alternativaCorreta" value="4"></input>
                                <label for="alternativaCorreta4">Alternativa 4</label>
                                <br>
                                <input type="radio" id="alternativaCorreta5" name="alternativaCorreta" value="5"></input>
                                <label for="alternativaCorreta5">Alternativa 5</label>
                            </div>
                            <div class="form-row">
                                <button type="button" class="btn btn-danger float-right" onclick="resetForm()">Limpar</button>
                                <button type="submit" class="btn btn-success float-right">Cadastrar</button>
                            </div>
                        </form>
                    </div>
                </div>
                <br>
                <div class="col">
                    <div class="footer">
                        <div id="message" class="alert alert-danger d-none">teste</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<script>

    var message = document.getElementById('message');
    var message2 = document.getElementById('message2');
    var form = document.getElementById('form');
    let total = 1;
    let partial = 0;
    let index = 0;

    function openModal(id) {
        document.getElementById('message2').classList.add('d-none');
        form.reset();
        $("#userId").val(id);
        if (id > 0) {
            showLoading();
            $("#file").attr('required', false);
            fetch(`<?= BASEURL ?>api/usuario/` + id, {
                method: 'GET',
                credentials: "same-origin",
                header: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                }
            }).then(response => {
                response.json().then(json => {
                    let user = json.message[0];
                    $("#name").val(user.name);
                    $("#email").val(user.email);
                    $("#phone").val(formatPhoneNumber(user.phone));
                    closeLoading();
                });
            });
        }
        $("#modal").modal('show');
    }

    function resetForm() {
        $("#nameFilter").val('');
        $("#emailFilter").val('');
        index = 0;
        partial = 0;
        total = 1;
        $("#userTable tbody").empty();
        getUsers();
    }

    function changeMessageType(type, id) {
        let message = document.getElementById(id);
        if (type === 'ok') {
            message.classList.remove('alert-danger');
            message.classList.remove('d-none');
            message.classList.add('alert-info');
        }

        if (type === 'error') {
            message.classList.remove('alert-info');
            message.classList.remove('d-none');
            message.classList.add('alert-danger');
        }
    }

    function generateTableBody(json) {
        let icons = `<i class="fa fa-pencil text-info" title="Editar ${json.name}" onclick="openModal(${json.id})"></i> `;
        icons += `<i class="fa fa-times text-danger" title="Deletar ${json.name}" onclick="removeUser(${json.id})"></i> `;
        return `
            <tr>
                <td class="text-center">${json.name}</td>
                <td class="text-center">${json.email}</td>
                <td class="text-center">${formatPhoneNumber(json.phone)}</td>
                <td class="text-center">${icons}</td>
            </tr>
        `;
    }

    function filter() {
        $("#userTable tbody").empty();
        index = 0;
        total = 1;
        partial = 0;
        getUsers();
    }

    function formatPhoneNumber(phoneNumberString) {
        var cleaned = ('' + phoneNumberString).replace(/\D/g, '');
        var match = cleaned.match(/^(\d{2})(\d{5})(\d{4})$/);
        if (match) {
            return '(' + match[1] + ') ' + match[2] + '-' + match[3];
        }
        return '';
    }

    function getUsers() {
        showLoading();
        let name = $("#nameFilter").val();
        let email = $("#emailFilter").val();
        fetch(`<?= BASEURL ?>api/cadastros/aluno/?name=${name}&email=${email}`, {
            method: 'GET',
            credentials: "same-origin",
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            response.json().then(json => {
                closeLoading();
                total = json.total;
                partial += json.partial;
                $("#total").text(total);
                $("#partial").text(partial);
                let users = json.message;
                let usersHtml = users.map(generateTableBody);
                $("#userTable tbody").append(usersHtml);
            });
        });
    }

    function removeUser(id) {
        showLoading();
        fetch(`<?= BASEURL ?>api/usuario/` + id, {
            method: 'DELETE',
            credentials: "same-origin",
            header: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
            }
        }).then(response => {
            response.json().then(json => {
                closeLoading();
                changeMessageType(json.status, 'message');
                message.innerText = json.message;
                if (json.status == 'ok') filter();
            });
        });
    }

    form.addEventListener(`submit`, e => {
        e.preventDefault();
        showLoading();
        let data = formDataToJson('form');
        fetch(`<?= BASEURL ?>api/cadastros/pergunta`, {
            method: 'POST',
            credentials: "same-origin",
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
        }).then(response => {
            response.json().then(json => {
                changeMessageType(json.status, 'message');
                message.innerText = json.message;
                closeLoading();
                if (json.status == 'ok') {
                    setTimeout(function () {
                        window.location.href = "<?= BASEURL ?>cadastros/pergunta/";
                    }, 2000);
                }
            });
        });
    });

    //form.addEventListener('submit', e => {
    //    e.preventDefault();
    //    showLoading();
    //    let formData = formDataToJson('userForm');
    //    let method = 'POST';
    //    if(formData.userId > 0) method = 'PUT';
    //    fetch(`<?//= BASEURL ?>//usuario/`, {
    //        method: 'POST',
    //        credentials: "same-origin",
    //        headers: {
    //            'Accept': 'application/json',
    //            'Content-Type': 'application/json',
    //        },
    //        body: JSON.stringify(formData),
    //    }).then(response => {
    //        response.json().then(json => {
    //            closeLoading();
    //            changeMessageType(json.status, 'message2');
    //            message2.innerText = json.message;
    //            if (json.status === 'ok') {
    //                $("#modal").modal('hide');
    //                filter();
    //            }
    //        });
    //    });
    //});

    $(document).ready(function () {
        getUsers();
    });

</script>